unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s
set -g mouse on

set -g extended-keys on
set -g allow-passthrough on
set -g -a terminal-features ',ghostty:RGB'
# set -g cursor-style 1
# set -ga terminal-features "xterm-kitty:extkeys"

# For a thin cursor
set -ga terminal-overrides ",*:Tc"
set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[6 q'

set-window-option -g mode-keys vi

# Switch panes using Prefix + hjkl
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-option -sg escape-time 10
set-option -g focus-events on

bind -n S-Enter send-keys "\e[13;2u"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'catppuccin/tmux#v2.3.0'
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style rounded
run ~/.tmux/plugins/tmux/catppuccin.tmux
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_directory}"
set -ag status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_ram}"
set -ag status-right "#{E:@catppuccin_status_date_time}"

set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-cpu'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
